import mongoose, { mongo } from "mongoose";

const ItinerarySchema = new mongoose.Schema({
    userId: { 
        type: mongoose.Schema.Types.ObjectId, 
        ref: "User", 
        required: true 
    },
    location: { 
        type: String, 
        required: true 
    },
    plan: { 
        type: String, 
        required: true 
    }, // Generated by LLM
    // stays: [{ type: String }], // Scraped stay names or IDs (url link to them directly)
    // travelOptions: [{ type: String }], // Scraped travel options (url link to them directly)
    // activities: [{ type: String }], // List of activities
    createdAt: { 
        type: Date, 
        default: Date.now 
    }
});

export const Itinerary = mongoose.model("Itinerary" , ItinerarySchema);
  